[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'forge-std/=lib/forge-std/src/',
    'chainlink/=lib/chainlink/contracts/',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/'
]

# Gas optimization settings
optimizer = true
optimizer_runs = 200
via_ir = true

# Solidity compiler settings
solc_version = "0.8.28"
evm_version = "cancun"

[rpc_endpoints]
avalanche_fuji = "${AVALANCHE_FUJI_RPC_URL}"
avalanche_mainnet = "${AVALANCHE_MAINNET_RPC_URL}"

# Etherscan API keys for verification (temporarily disabled)
# [etherscan]
# avalanche_fuji = { key = "${SNOWTRACE_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }
# avalanche = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options 